app = "grand-backend"
primary_region = "sin"  

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5050"

[http_service]
  internal_port = 5050
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 